version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
environment:
  SERVICESTACK_LICENSE:
    secure: 5zYTw+1lLlf6ydh05spg4huc/S2VUb+Ka5b3etCB8bvVQTAlMabBx7mcTxadOnCJo4EwPPc94TyDFEhJ031XcSds4I6NL3TEVzcY1y73tibAYaejOgWs5kNzcIjLbemn/SqHw7bvrmUSJVs2M9UFYkqyv/GaDO7O/j/VrZSZOB6KwW4QHanV7RDZpSnepoQ5fPXatIbimF3KXGTQGMHcffTBjpBsvfzOOc05fXtuvfLlv8eG3fqOvN7IUlyC9EOCBgDr6JjJFKmm9CbPNChkaLnyieMvWf2GRUSZaOjV2MmBvdSmDsIrNW26rUS+K4V5+NQ2gGWkxJApOMsg6+QvVf7UGR4npVkgkelYSW1QMVfTWxNCbLd4bEi8PRkCgxLSM07VWvNrFBPUZWkEQtNCaBHhhvbtsBOKr0CpEPJKFO4L+p7AG6wDhPED7vk3g81p
  matrix:
  - test_type: Unit.Testing
    test_category: Unit
  - test_type: Unit.Testing.Architecture
    test_category: Unit.Architecture
  - test_type: Integration.Testing.Web
    test_category: Integration.Web
#  - test_type: Integration.Testing.Storage
#    test_category: Integration.Storage
matrix:
    fast_finish: false
install:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/jezzsantos/queryany/master/ci/set-version-from-globalassemblyinfo-assemblyinformationalversion.ps1'))
- ps: nuget install redis-64 -excludeversion
- ps: redis-64\tools\redis-server.exe --service-install
- ps: redis-64\tools\redis-server.exe --service-start
before_build:
- cmd: nuget restore src\QueryAny.sln
- cmd: xcopy "samples\ri\Storage.IntegrationTests\appsettings.CI.json" "samples\ri\Storage.IntegrationTests\appsettings.json" /R /Y
build:
  project: src\QueryAny.sln
  verbosity: minimal
test_script:
- ps: dotnet dev-certs https --trust
- ps: dotnet test --configuration $env:CONFIGURATION --filter Category=$env:test_category src\QueryAny.sln
artifacts:
- path: '**\QueryAny.*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 8aeZAmikK85S7COgBdnSeW5g89bi87eL30OvCW2H/m3jDE5hHsnHOBrObwsOW8PF
  skip_symbols: true
  on:
    branch: master