//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryAny.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QueryAny.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot &apos;Take&apos; more than once.
        /// </summary>
        public static string QueriedEntities_LimitAlreadySet {
            get {
                return ResourceManager.GetString("QueriedEntities_LimitAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot &apos;Skip&apos; more than once.
        /// </summary>
        public static string QueriedEntities_OffsetAlreadySet {
            get {
                return ResourceManager.GetString("QueriedEntities_OffsetAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot &apos;ByBy&apos; more than once.
        /// </summary>
        public static string QueriedEntities_OrderAlreadySet {
            get {
                return ResourceManager.GetString("QueriedEntities_OrderAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot &apos;SelectFromJoin&apos; on entity {0}, because no joins are yet defined.
        /// </summary>
        public static string QueryClause_SelectFromJoin_NoJoins {
            get {
                return ResourceManager.GetString("QueryClause_SelectFromJoin_NoJoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot &apos;SelectFromJoin&apos; on entity {0}, because no join for that entity is yet defined.
        /// </summary>
        public static string QueryClause_SelectFromJoin_UnknownJoin {
            get {
                return ResourceManager.GetString("QueryClause_SelectFromJoin_UnknownJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot &apos;Take&apos; less than 0 results.
        /// </summary>
        public static string ResultOptions_InvalidLimit {
            get {
                return ResourceManager.GetString("ResultOptions_InvalidLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot &apos;Skip&apos; less than 0 results.
        /// </summary>
        public static string ResultOptions_InvalidOffset {
            get {
                return ResourceManager.GetString("ResultOptions_InvalidOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot &apos;OrderBy&apos; null.
        /// </summary>
        public static string ResultOptions_InvalidOrderBy {
            get {
                return ResourceManager.GetString("ResultOptions_InvalidOrderBy", resourceCulture);
            }
        }
    }
}
