name: Build Test and Docs

on: [ push, pull_request ]

env:
  IS_CI_BUILD: 'true'
  SOLUTION_PATH: 'src/QueryAny.sln'
  TESTINGONLY_BUILD_CONFIGURATION: 'Debug'
  RELEASE_BUILD_CONFIGURATION: 'Release'

jobs:
  build-test:
    runs-on: windows-latest
    timeout-minutes: 15
    env:
      SERVICESTACK_LICENSE: ${{secrets.SERVICESTACK_LICENSE}}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore "${{env.SOLUTION_PATH}}"
      - name: Build for Release
        run: dotnet build "${{env.SOLUTION_PATH}}" --no-restore --configuration ${{env.RELEASE_BUILD_CONFIGURATION}}
      - name: Build for Testing
        run: dotnet build "${{env.SOLUTION_PATH}}" --no-restore --configuration ${{env.TESTINGONLY_BUILD_CONFIGURATION}}
      - name: Unit Test
        run: dotnet test --filter "Category=Unit|Category=Unit.Architecture" "${{env.SOLUTION_PATH}}" --no-build --verbosity normal
# Unable to run integration tests until we can install a self-signed certificate and trust it
#      - name: Integration Test
#        run: dotnet test --filter "Category=Integration.Web" "${{env.SOLUTION_PATH}}" --no-build --verbosity normal
#  publish-docs:
#    if: github.ref == 'refs/heads/main'
#    runs-on: windows-latest
#    timeout-minutes: 15
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.x
#      - name: Deploy Docs
#        run: |
#          pip install mkdocs
#          pip install mkdocs-material
#          pip install mkdocs-glightbox
#          mkdocs gh-deploy --force --clean --verbose