name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-preview'

env:
  IS_CI_BUILD: 'true'
  SOLUTION_PATH: 'src/QueryAny.sln'
  LIBRARYPROJECT_PATH: 'src/QueryAny/QueryAny.csproj'
  BUILD_CONFIGURATION: 'Release'
  NUGET_PACKAGE_DIR: 'src/QueryAny/bin/Release'
  NUGET_APIKEY: '${{secrets.NUGET_APIKEY}}'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore "${{env.SOLUTION_PATH}}"
      - name: Build
        run: dotnet build "${{env.SOLUTION_PATH}}" --no-restore --configuration ${{env.BUILD_CONFIGURATION}}
      - name: Package NuGet
        run: dotnet pack --configuration ${{env.BUILD_CONFIGURATION}} "${{env.LIBRARYPROJECT_PATH}}"
      - name: Publish NuGet
        run: |
          cd "${{env.NUGET_PACKAGE_DIR}}"
          dotnet nuget push "*.nupkg" --api-key ${{env.NUGET_APIKEY}} --source "https://api.nuget.org/v3/index.json"